// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NPI.Server.Data;

#nullable disable

namespace NPI.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260722014802_NPI4")]
    partial class NPI4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NPI.Server.Models.AuditLogs", b =>
                {
                    b.Property<int>("log_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("log_id"));

                    b.Property<string>("action")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("ip_address")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("new_value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("old_value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("proj_id")
                        .HasColumnType("int");

                    b.Property<int?>("record_id")
                        .HasColumnType("int");

                    b.Property<string>("table_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("log_id");

                    b.HasIndex("proj_id");

                    b.HasIndex("user_id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("NPI.Server.Models.Customers", b =>
                {
                    b.Property<int>("cust_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cust_id"));

                    b.Property<string>("comp_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("contact_email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("contact_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("contact_phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("cust_addr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.HasKey("cust_id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("NPI.Server.Models.Departments", b =>
                {
                    b.Property<int>("dept_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("dept_id"));

                    b.Property<string>("color_hex")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("dept_code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("dept_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("is_assignable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("dept_id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("NPI.Server.Models.Enquiries", b =>
                {
                    b.Property<int>("enquiry_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("enquiry_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("created_by")
                        .HasColumnType("int");

                    b.Property<int>("cust_id")
                        .HasColumnType("int");

                    b.Property<string>("enquiry_no")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("npi_category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("proj_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("submitted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("enquiry_id");

                    b.HasIndex("created_by");

                    b.HasIndex("cust_id");

                    b.HasIndex("enquiry_no")
                        .IsUnique();

                    b.HasIndex("proj_id");

                    b.ToTable("Enquiries");
                });

            modelBuilder.Entity("NPI.Server.Models.EnquiryCustomerRef", b =>
                {
                    b.Property<int>("enquiry_id")
                        .HasColumnType("int");

                    b.Property<string>("mould_ownership")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("enquiry_id");

                    b.ToTable("EnquiryCustomerRef");
                });

            modelBuilder.Entity("NPI.Server.Models.EnquiryFieldValues", b =>
                {
                    b.Property<int>("value_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("value_id"));

                    b.Property<int>("enquiry_id")
                        .HasColumnType("int");

                    b.Property<string>("field_key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("field_value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("section_key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("value_id");

                    b.HasIndex("enquiry_id", "section_key", "field_key")
                        .IsUnique()
                        .HasDatabaseName("IX_EnquiryFieldValues_Unique");

                    b.ToTable("EnquiryFieldValues");
                });

            modelBuilder.Entity("NPI.Server.Models.Files", b =>
                {
                    b.Property<int>("file_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("file_id"));

                    b.Property<string>("content_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<int?>("dept_id")
                        .HasColumnType("int");

                    b.Property<int?>("enquiry_id")
                        .HasColumnType("int");

                    b.Property<string>("file_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("file_path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("file_size")
                        .HasColumnType("bigint");

                    b.Property<int>("file_version")
                        .HasColumnType("int");

                    b.Property<bool>("is_latest")
                        .HasColumnType("bit");

                    b.Property<int?>("proj_id")
                        .HasColumnType("int");

                    b.Property<int?>("replaced_by")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("task_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("upload_by")
                        .HasColumnType("int");

                    b.HasKey("file_id");

                    b.HasIndex("dept_id");

                    b.HasIndex("enquiry_id");

                    b.HasIndex("proj_id");

                    b.HasIndex("replaced_by");

                    b.HasIndex("task_id");

                    b.HasIndex("upload_by");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("NPI.Server.Models.Notifications", b =>
                {
                    b.Property<int>("notif_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("notif_id"));

                    b.Property<string>("body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_read")
                        .HasColumnType("bit");

                    b.Property<string>("notif_type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("proj_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("read_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("sent_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("subject")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("task_id")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("notif_id");

                    b.HasIndex("proj_id");

                    b.HasIndex("task_id");

                    b.HasIndex("user_id", "is_read", "created_at")
                        .HasDatabaseName("IX_Notifications_User_Unread");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("NPI.Server.Models.NpiCategory", b =>
                {
                    b.Property<int>("category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("category_id"));

                    b.Property<string>("category_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("display_order")
                        .HasColumnType("int");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("category_id");

                    b.ToTable("NpiCategories");
                });

            modelBuilder.Entity("NPI.Server.Models.NpiFormField", b =>
                {
                    b.Property<int>("field_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("field_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("display_order")
                        .HasColumnType("int");

                    b.Property<string>("field_key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("field_label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("field_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<bool>("is_required")
                        .HasColumnType("bit");

                    b.Property<string>("options")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("section_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("field_id");

                    b.HasIndex("section_id");

                    b.ToTable("NpiFormFields");
                });

            modelBuilder.Entity("NPI.Server.Models.NpiFormSection", b =>
                {
                    b.Property<int>("section_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("section_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("display_order")
                        .HasColumnType("int");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("section_key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("section_label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("trigger_keywords")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("section_id");

                    b.ToTable("NpiFormSections");
                });

            modelBuilder.Entity("NPI.Server.Models.ProjectRevisions", b =>
                {
                    b.Property<int>("revision_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("revision_id"));

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("new_target_date")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("previous_target_date")
                        .HasColumnType("date");

                    b.Property<int>("proj_id")
                        .HasColumnType("int");

                    b.Property<int>("revised_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("revision_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("revision_notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("revision_number")
                        .HasColumnType("int");

                    b.HasKey("revision_id");

                    b.HasIndex("proj_id");

                    b.HasIndex("revised_by");

                    b.ToTable("ProjectRevisions");
                });

            modelBuilder.Entity("NPI.Server.Models.ProjectRoles", b =>
                {
                    b.Property<int>("proj_role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("proj_role_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("proj_role_id");

                    b.ToTable("ProjectRoles");
                });

            modelBuilder.Entity("NPI.Server.Models.ProjectStatusHistory", b =>
                {
                    b.Property<int>("history_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("history_id"));

                    b.Property<DateTime>("changed_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("changed_by")
                        .HasColumnType("int");

                    b.Property<string>("new_status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("old_status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("proj_id")
                        .HasColumnType("int");

                    b.Property<string>("remark")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("history_id");

                    b.HasIndex("changed_by");

                    b.HasIndex("proj_id");

                    b.ToTable("ProjectStatusHistory");
                });

            modelBuilder.Entity("NPI.Server.Models.ProjectTeams", b =>
                {
                    b.Property<int>("team_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("team_id"));

                    b.Property<int?>("assigned_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("proj_id")
                        .HasColumnType("int");

                    b.Property<string>("role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("team_id");

                    b.HasIndex("assigned_by");

                    b.HasIndex("user_id");

                    b.HasIndex("proj_id", "user_id")
                        .IsUnique()
                        .HasDatabaseName("IX_ProjectTeams_ProjUser");

                    b.ToTable("ProjectTeams");
                });

            modelBuilder.Entity("NPI.Server.Models.Projects", b =>
                {
                    b.Property<int>("proj_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("proj_id"));

                    b.Property<DateOnly?>("actual_completion_date")
                        .HasColumnType("date");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("created_by")
                        .HasColumnType("int");

                    b.Property<int>("cust_id")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("enquiry_date")
                        .HasColumnType("date");

                    b.Property<bool>("machine_purchase_required")
                        .HasColumnType("bit");

                    b.Property<bool>("pilot_mould_required")
                        .HasColumnType("bit");

                    b.Property<string>("priority")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("proj_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("proj_no")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("project_start_date")
                        .HasColumnType("date");

                    b.Property<string>("status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("storage_path")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("target_completion_date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("proj_id");

                    b.HasIndex("created_by");

                    b.HasIndex("cust_id");

                    b.HasIndex("proj_no")
                        .IsUnique();

                    b.HasIndex("updated_by");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("NPI.Server.Models.RolePermissions", b =>
                {
                    b.Property<int>("permission_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("permission_id"));

                    b.Property<bool>("can_approve")
                        .HasColumnType("bit");

                    b.Property<bool>("can_create")
                        .HasColumnType("bit");

                    b.Property<bool>("can_delete")
                        .HasColumnType("bit");

                    b.Property<bool>("can_read")
                        .HasColumnType("bit");

                    b.Property<bool>("can_update")
                        .HasColumnType("bit");

                    b.Property<string>("resource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.HasKey("permission_id");

                    b.HasIndex("role_id");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("NPI.Server.Models.Roles", b =>
                {
                    b.Property<int>("role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("role_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("role_id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("NPI.Server.Models.TaskRevisions", b =>
                {
                    b.Property<int>("task_revision_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("task_revision_id"));

                    b.Property<int?>("dept_id")
                        .HasColumnType("int");

                    b.Property<float?>("duration")
                        .HasColumnType("real");

                    b.Property<DateOnly?>("new_end_date")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("new_start_date")
                        .HasColumnType("date");

                    b.Property<string>("note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("old_end_date")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("old_start_date")
                        .HasColumnType("date");

                    b.Property<DateTime>("revised_on")
                        .HasColumnType("datetime2");

                    b.Property<int?>("revision_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("task_id")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("task_revision_id");

                    b.HasIndex("dept_id");

                    b.HasIndex("revision_id");

                    b.HasIndex("task_id");

                    b.ToTable("TaskRevisions");
                });

            modelBuilder.Entity("NPI.Server.Models.TaskTemplates", b =>
                {
                    b.Property<int>("template_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("template_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("default_duration")
                        .HasColumnType("int");

                    b.Property<int>("dept_id")
                        .HasColumnType("int");

                    b.Property<int>("display_order")
                        .HasColumnType("int");

                    b.Property<bool>("has_link")
                        .HasColumnType("bit");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("stage_id")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("task_code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("template_id");

                    b.HasIndex("dept_id");

                    b.HasIndex("stage_id", "task_code")
                        .IsUnique()
                        .HasDatabaseName("IX_TaskTemplates_Stage_Code");

                    b.ToTable("TaskTemplates");
                });

            modelBuilder.Entity("NPI.Server.Models.Tasks", b =>
                {
                    b.Property<int>("task_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("task_id"));

                    b.Property<DateOnly?>("actual_end_date")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("actual_start_date")
                        .HasColumnType("date");

                    b.Property<int?>("assigned_by")
                        .HasColumnType("int");

                    b.Property<int?>("assigned_to")
                        .HasColumnType("int");

                    b.Property<DateTime?>("completed_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("dept_id")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("duration")
                        .HasColumnType("real");

                    b.Property<int?>("parent_task_id")
                        .HasColumnType("int");

                    b.Property<float?>("per_complete")
                        .HasColumnType("real");

                    b.Property<DateOnly?>("planned_end_date")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("planned_start_date")
                        .HasColumnType("date");

                    b.Property<string>("priority")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("proj_id")
                        .HasColumnType("int");

                    b.Property<string>("stage_id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("task_code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("task_id");

                    b.HasIndex("assigned_by");

                    b.HasIndex("assigned_to");

                    b.HasIndex("dept_id");

                    b.HasIndex("parent_task_id");

                    b.HasIndex("proj_id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("NPI.Server.Models.UserSessions", b =>
                {
                    b.Property<string>("session_id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("ip_address")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("token_hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_agent")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("session_id");

                    b.HasIndex("user_id");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("NPI.Server.Models.Users", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("dept_id")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("full_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("last_login")
                        .HasColumnType("datetime2");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("role_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("user_id");

                    b.HasIndex("dept_id");

                    b.HasIndex("email")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex("role_id");

                    b.HasIndex("username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NPI.Server.Models.AuditLogs", b =>
                {
                    b.HasOne("NPI.Server.Models.Projects", "Project")
                        .WithMany("AuditLogs")
                        .HasForeignKey("proj_id");

                    b.HasOne("NPI.Server.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("user_id");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NPI.Server.Models.Enquiries", b =>
                {
                    b.HasOne("NPI.Server.Models.Users", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("created_by")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPI.Server.Models.Customers", "Customer")
                        .WithMany()
                        .HasForeignKey("cust_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPI.Server.Models.Projects", "Project")
                        .WithMany()
                        .HasForeignKey("proj_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("NPI.Server.Models.EnquiryCustomerRef", b =>
                {
                    b.HasOne("NPI.Server.Models.Enquiries", "Enquiry")
                        .WithOne("CustomerRef")
                        .HasForeignKey("NPI.Server.Models.EnquiryCustomerRef", "enquiry_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enquiry");
                });

            modelBuilder.Entity("NPI.Server.Models.EnquiryFieldValues", b =>
                {
                    b.HasOne("NPI.Server.Models.Enquiries", "Enquiry")
                        .WithMany("FieldValues")
                        .HasForeignKey("enquiry_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enquiry");
                });

            modelBuilder.Entity("NPI.Server.Models.Files", b =>
                {
                    b.HasOne("NPI.Server.Models.Departments", "Department")
                        .WithMany("Files")
                        .HasForeignKey("dept_id");

                    b.HasOne("NPI.Server.Models.Enquiries", "Enquiry")
                        .WithMany("Files")
                        .HasForeignKey("enquiry_id");

                    b.HasOne("NPI.Server.Models.Projects", "Project")
                        .WithMany("Files")
                        .HasForeignKey("proj_id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NPI.Server.Models.Files", "ReplacedByFile")
                        .WithMany()
                        .HasForeignKey("replaced_by")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NPI.Server.Models.Tasks", "Task")
                        .WithMany("Files")
                        .HasForeignKey("task_id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NPI.Server.Models.Users", "UploadByUser")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("upload_by")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Enquiry");

                    b.Navigation("Project");

                    b.Navigation("ReplacedByFile");

                    b.Navigation("Task");

                    b.Navigation("UploadByUser");
                });

            modelBuilder.Entity("NPI.Server.Models.Notifications", b =>
                {
                    b.HasOne("NPI.Server.Models.Projects", "Project")
                        .WithMany("Notifications")
                        .HasForeignKey("proj_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NPI.Server.Models.Tasks", "Task")
                        .WithMany()
                        .HasForeignKey("task_id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NPI.Server.Models.Users", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NPI.Server.Models.NpiFormField", b =>
                {
                    b.HasOne("NPI.Server.Models.NpiFormSection", "Section")
                        .WithMany("Fields")
                        .HasForeignKey("section_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("NPI.Server.Models.ProjectRevisions", b =>
                {
                    b.HasOne("NPI.Server.Models.Projects", "Project")
                        .WithMany("ProjectRevisions")
                        .HasForeignKey("proj_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPI.Server.Models.Users", "RevisedByUser")
                        .WithMany()
                        .HasForeignKey("revised_by")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("RevisedByUser");
                });

            modelBuilder.Entity("NPI.Server.Models.ProjectStatusHistory", b =>
                {
                    b.HasOne("NPI.Server.Models.Users", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("changed_by")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPI.Server.Models.Projects", "Project")
                        .WithMany("ProjectStatusHistories")
                        .HasForeignKey("proj_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("NPI.Server.Models.ProjectTeams", b =>
                {
                    b.HasOne("NPI.Server.Models.Users", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("assigned_by")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NPI.Server.Models.Projects", "Project")
                        .WithMany("ProjectTeams")
                        .HasForeignKey("proj_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPI.Server.Models.Users", "User")
                        .WithMany("ProjectTeams")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NPI.Server.Models.Projects", b =>
                {
                    b.HasOne("NPI.Server.Models.Users", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("created_by")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NPI.Server.Models.Customers", "Customer")
                        .WithMany("Projects")
                        .HasForeignKey("cust_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPI.Server.Models.Users", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("updated_by")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("NPI.Server.Models.RolePermissions", b =>
                {
                    b.HasOne("NPI.Server.Models.Roles", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NPI.Server.Models.TaskRevisions", b =>
                {
                    b.HasOne("NPI.Server.Models.Departments", "Department")
                        .WithMany()
                        .HasForeignKey("dept_id");

                    b.HasOne("NPI.Server.Models.ProjectRevisions", "Revision")
                        .WithMany("TaskRevisions")
                        .HasForeignKey("revision_id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NPI.Server.Models.Tasks", "Task")
                        .WithMany("TaskRevisions")
                        .HasForeignKey("task_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Revision");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("NPI.Server.Models.TaskTemplates", b =>
                {
                    b.HasOne("NPI.Server.Models.Departments", "Department")
                        .WithMany()
                        .HasForeignKey("dept_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("NPI.Server.Models.Tasks", b =>
                {
                    b.HasOne("NPI.Server.Models.Users", "AssignedByUser")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("assigned_by")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NPI.Server.Models.Users", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("assigned_to");

                    b.HasOne("NPI.Server.Models.Departments", "Department")
                        .WithMany()
                        .HasForeignKey("dept_id");

                    b.HasOne("NPI.Server.Models.Tasks", "ParentTask")
                        .WithMany("SubTasks")
                        .HasForeignKey("parent_task_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NPI.Server.Models.Projects", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("proj_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("AssignedToUser");

                    b.Navigation("Department");

                    b.Navigation("ParentTask");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("NPI.Server.Models.UserSessions", b =>
                {
                    b.HasOne("NPI.Server.Models.Users", "User")
                        .WithMany("UserSessions")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NPI.Server.Models.Users", b =>
                {
                    b.HasOne("NPI.Server.Models.Departments", "Department")
                        .WithMany("Users")
                        .HasForeignKey("dept_id");

                    b.HasOne("NPI.Server.Models.Roles", "Role")
                        .WithMany("Users")
                        .HasForeignKey("role_id");

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NPI.Server.Models.Customers", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("NPI.Server.Models.Departments", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NPI.Server.Models.Enquiries", b =>
                {
                    b.Navigation("CustomerRef");

                    b.Navigation("FieldValues");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("NPI.Server.Models.NpiFormSection", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("NPI.Server.Models.ProjectRevisions", b =>
                {
                    b.Navigation("TaskRevisions");
                });

            modelBuilder.Entity("NPI.Server.Models.Projects", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Files");

                    b.Navigation("Notifications");

                    b.Navigation("ProjectRevisions");

                    b.Navigation("ProjectStatusHistories");

                    b.Navigation("ProjectTeams");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("NPI.Server.Models.Roles", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NPI.Server.Models.Tasks", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("SubTasks");

                    b.Navigation("TaskRevisions");
                });

            modelBuilder.Entity("NPI.Server.Models.Users", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("Notifications");

                    b.Navigation("ProjectTeams");

                    b.Navigation("UploadedFiles");

                    b.Navigation("UserSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
