// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NPI.Server.Data;

#nullable disable

namespace NPI.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NPI.Server.Models.Approvals", b =>
                {
                    b.Property<int>("appr_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("appr_id"));

                    b.Property<int?>("appr_level")
                        .HasColumnType("int");

                    b.Property<int?>("appr_order")
                        .HasColumnType("int");

                    b.Property<string>("appr_type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("approved_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("apprv_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("file_id")
                        .HasColumnType("int");

                    b.Property<int>("proj_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("rejected_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("task_id")
                        .HasColumnType("int");

                    b.HasKey("appr_id");

                    b.HasIndex("apprv_by");

                    b.HasIndex("file_id");

                    b.HasIndex("proj_id");

                    b.HasIndex("task_id");

                    b.ToTable("Approvals");
                });

            modelBuilder.Entity("NPI.Server.Models.AuditLogs", b =>
                {
                    b.Property<int>("log_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("log_id"));

                    b.Property<string>("action")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("ip_address")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("new_value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("old_value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("proj_id")
                        .HasColumnType("int");

                    b.Property<int?>("record_id")
                        .HasColumnType("int");

                    b.Property<string>("table_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("log_id");

                    b.HasIndex("proj_id");

                    b.HasIndex("user_id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("NPI.Server.Models.Comments", b =>
                {
                    b.Property<int>("comment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("comment_id"));

                    b.Property<string>("comment_text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("proj_id")
                        .HasColumnType("int");

                    b.Property<int?>("task_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("comment_id");

                    b.HasIndex("proj_id");

                    b.HasIndex("task_id");

                    b.HasIndex("user_id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("NPI.Server.Models.Customers", b =>
                {
                    b.Property<int>("cust_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cust_id"));

                    b.Property<string>("comp_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("contact_email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("contact_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("contact_phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("cust_addr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.HasKey("cust_id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("NPI.Server.Models.Departments", b =>
                {
                    b.Property<int>("dept_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("dept_id"));

                    b.Property<int?>("Projectsproj_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("dept_code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("dept_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("dept_id");

                    b.HasIndex("Projectsproj_id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("NPI.Server.Models.DocumentTypes", b =>
                {
                    b.Property<int>("doc_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("doc_type_id"));

                    b.Property<int?>("dept_id")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("is_required")
                        .HasColumnType("bit");

                    b.Property<string>("type_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("doc_type_id");

                    b.HasIndex("dept_id");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("NPI.Server.Models.Enquiries", b =>
                {
                    b.Property<int>("enquiry_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("enquiry_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("created_by")
                        .HasColumnType("int");

                    b.Property<int>("cust_id")
                        .HasColumnType("int");

                    b.Property<string>("enquiry_no")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("npi_category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("proj_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("submitted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("enquiry_id");

                    b.HasIndex("created_by");

                    b.HasIndex("cust_id");

                    b.HasIndex("enquiry_no")
                        .IsUnique();

                    b.HasIndex("proj_id");

                    b.ToTable("Enquiries");
                });

            modelBuilder.Entity("NPI.Server.Models.EnquiryCustomerRef", b =>
                {
                    b.Property<int>("enquiry_id")
                        .HasColumnType("int");

                    b.Property<string>("mould_ownership")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("enquiry_id");

                    b.ToTable("EnquiryCustomerRef");
                });

            modelBuilder.Entity("NPI.Server.Models.EnquiryGeneralInfo", b =>
                {
                    b.Property<int>("enquiry_id")
                        .HasColumnType("int");

                    b.Property<string>("cap_bottle_source")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("cap_seal")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("capping_method")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("color")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("company_name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("estimated_qty_per_year")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("estimated_required_date")
                        .HasColumnType("date");

                    b.Property<string>("filling_content")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("hot_cold_filling")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("material_used")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("neck_size_mm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("qty_first_submission")
                        .HasColumnType("int");

                    b.Property<string>("shape")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float?>("weight_g")
                        .HasColumnType("real");

                    b.HasKey("enquiry_id");

                    b.ToTable("EnquiryGeneralInfo");
                });

            modelBuilder.Entity("NPI.Server.Models.EnquirySealInfo", b =>
                {
                    b.Property<int>("enquiry_id")
                        .HasColumnType("int");

                    b.Property<string>("apply_to_product")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("customer_name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("estimated_required_date")
                        .HasColumnType("date");

                    b.Property<string>("other_requirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("qty_first_submission")
                        .HasColumnType("int");

                    b.Property<string>("reason_of_change")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("enquiry_id");

                    b.ToTable("EnquirySealInfo");
                });

            modelBuilder.Entity("NPI.Server.Models.Files", b =>
                {
                    b.Property<int>("file_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("file_id"));

                    b.Property<string>("content_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("dept_id")
                        .HasColumnType("int");

                    b.Property<int?>("doc_type_id")
                        .HasColumnType("int");

                    b.Property<int?>("enquiry_id")
                        .HasColumnType("int");

                    b.Property<string>("file_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("file_path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("file_size")
                        .HasColumnType("bigint");

                    b.Property<int>("file_version")
                        .HasColumnType("int");

                    b.Property<bool>("is_latest")
                        .HasColumnType("bit");

                    b.Property<int>("proj_id")
                        .HasColumnType("int");

                    b.Property<int?>("replaced_by")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("task_id")
                        .HasColumnType("int");

                    b.Property<int>("upload_by")
                        .HasColumnType("int");

                    b.HasKey("file_id");

                    b.HasIndex("dept_id");

                    b.HasIndex("doc_type_id");

                    b.HasIndex("enquiry_id");

                    b.HasIndex("proj_id");

                    b.HasIndex("replaced_by");

                    b.HasIndex("task_id");

                    b.HasIndex("upload_by");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("NPI.Server.Models.Milestones", b =>
                {
                    b.Property<int>("milestone_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("milestone_id"));

                    b.Property<DateOnly?>("actual_date")
                        .HasColumnType("date");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("milestone_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("planned_date")
                        .HasColumnType("date");

                    b.Property<int>("proj_id")
                        .HasColumnType("int");

                    b.Property<int?>("responsible_dept_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("task_id")
                        .HasColumnType("int");

                    b.HasKey("milestone_id");

                    b.HasIndex("proj_id");

                    b.HasIndex("responsible_dept_id");

                    b.HasIndex("task_id")
                        .IsUnique();

                    b.ToTable("Milestones");
                });

            modelBuilder.Entity("NPI.Server.Models.Notifications", b =>
                {
                    b.Property<int>("notif_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("notif_id"));

                    b.Property<string>("body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("notif_type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("proj_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("read_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("sent_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("subject")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("notif_id");

                    b.HasIndex("proj_id");

                    b.HasIndex("user_id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("NPI.Server.Models.ProjectRevisions", b =>
                {
                    b.Property<int>("revision_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("revision_id"));

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("new_target_date")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("previous_target_date")
                        .HasColumnType("date");

                    b.Property<int>("proj_id")
                        .HasColumnType("int");

                    b.Property<int>("revised_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("revision_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("revision_notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("revision_number")
                        .HasColumnType("int");

                    b.HasKey("revision_id");

                    b.HasIndex("proj_id");

                    b.HasIndex("revised_by");

                    b.ToTable("ProjectRevisions");
                });

            modelBuilder.Entity("NPI.Server.Models.ProjectStatusHistory", b =>
                {
                    b.Property<int>("history_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("history_id"));

                    b.Property<DateTime>("changed_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("changed_by")
                        .HasColumnType("int");

                    b.Property<string>("new_status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("old_status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("proj_id")
                        .HasColumnType("int");

                    b.Property<string>("remark")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("history_id");

                    b.HasIndex("changed_by");

                    b.HasIndex("proj_id");

                    b.ToTable("ProjectStatusHistory");
                });

            modelBuilder.Entity("NPI.Server.Models.ProjectTeams", b =>
                {
                    b.Property<int>("team_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("team_id"));

                    b.Property<int?>("assigned_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("proj_id")
                        .HasColumnType("int");

                    b.Property<string>("role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("team_id");

                    b.HasIndex("assigned_by");

                    b.HasIndex("proj_id");

                    b.HasIndex("user_id");

                    b.ToTable("ProjectTeams");
                });

            modelBuilder.Entity("NPI.Server.Models.Projects", b =>
                {
                    b.Property<int>("proj_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("proj_id"));

                    b.Property<DateOnly?>("actual_completion_date")
                        .HasColumnType("date");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("created_by")
                        .HasColumnType("int");

                    b.Property<int>("cust_id")
                        .HasColumnType("int");

                    b.Property<int>("dept_id")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("enquiry_date")
                        .HasColumnType("date");

                    b.Property<string>("priority")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("proj_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("proj_no")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("project_start_date")
                        .HasColumnType("date");

                    b.Property<string>("status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("storage_path")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("target_completion_date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("proj_id");

                    b.HasIndex("created_by");

                    b.HasIndex("cust_id");

                    b.HasIndex("proj_no")
                        .IsUnique();

                    b.HasIndex("updated_by");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("NPI.Server.Models.RolePermissions", b =>
                {
                    b.Property<int>("permission_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("permission_id"));

                    b.Property<bool>("can_approve")
                        .HasColumnType("bit");

                    b.Property<bool>("can_create")
                        .HasColumnType("bit");

                    b.Property<bool>("can_delete")
                        .HasColumnType("bit");

                    b.Property<bool>("can_read")
                        .HasColumnType("bit");

                    b.Property<bool>("can_update")
                        .HasColumnType("bit");

                    b.Property<string>("resource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.HasKey("permission_id");

                    b.HasIndex("role_id");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("NPI.Server.Models.Roles", b =>
                {
                    b.Property<int>("role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("role_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("role_id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("NPI.Server.Models.TaskRevisions", b =>
                {
                    b.Property<int>("task_revision_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("task_revision_id"));

                    b.Property<int?>("dept_id")
                        .HasColumnType("int");

                    b.Property<float?>("duration")
                        .HasColumnType("real");

                    b.Property<DateOnly?>("new_end_date")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("new_start_date")
                        .HasColumnType("date");

                    b.Property<string>("note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("old_end_date")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("old_start_date")
                        .HasColumnType("date");

                    b.Property<DateTime>("revised_on")
                        .HasColumnType("datetime2");

                    b.Property<int>("revision_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("task_id")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("task_revision_id");

                    b.HasIndex("dept_id");

                    b.HasIndex("revision_id");

                    b.HasIndex("task_id");

                    b.ToTable("TaskRevisions");
                });

            modelBuilder.Entity("NPI.Server.Models.Tasks", b =>
                {
                    b.Property<int>("task_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("task_id"));

                    b.Property<DateOnly?>("actual_end_date")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("actual_start_date")
                        .HasColumnType("date");

                    b.Property<int?>("assigned_by")
                        .HasColumnType("int");

                    b.Property<int?>("assigned_to")
                        .HasColumnType("int");

                    b.Property<DateTime?>("completed_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("dept_id")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("duration")
                        .HasColumnType("real");

                    b.Property<int?>("parent_task_id")
                        .HasColumnType("int");

                    b.Property<float?>("per_complete")
                        .HasColumnType("real");

                    b.Property<DateOnly?>("planned_end_date")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("planned_start_date")
                        .HasColumnType("date");

                    b.Property<string>("priority")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("proj_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("task_id");

                    b.HasIndex("assigned_by");

                    b.HasIndex("assigned_to");

                    b.HasIndex("dept_id");

                    b.HasIndex("parent_task_id");

                    b.HasIndex("proj_id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("NPI.Server.Models.UserSessions", b =>
                {
                    b.Property<string>("session_id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("ip_address")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("token_hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_agent")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("session_id");

                    b.HasIndex("user_id");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("NPI.Server.Models.Users", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("dept_id")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("full_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("last_login")
                        .HasColumnType("datetime2");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("role_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("user_id");

                    b.HasIndex("dept_id");

                    b.HasIndex("email")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex("role_id");

                    b.HasIndex("username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NPI.Server.Models.Approvals", b =>
                {
                    b.HasOne("NPI.Server.Models.Users", "ApprovedByUser")
                        .WithMany("Approvals")
                        .HasForeignKey("apprv_by");

                    b.HasOne("NPI.Server.Models.Files", "File")
                        .WithMany("Approvals")
                        .HasForeignKey("file_id");

                    b.HasOne("NPI.Server.Models.Projects", "Project")
                        .WithMany("Approvals")
                        .HasForeignKey("proj_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPI.Server.Models.Tasks", "Task")
                        .WithMany("Approvals")
                        .HasForeignKey("task_id");

                    b.Navigation("ApprovedByUser");

                    b.Navigation("File");

                    b.Navigation("Project");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("NPI.Server.Models.AuditLogs", b =>
                {
                    b.HasOne("NPI.Server.Models.Projects", "Project")
                        .WithMany("AuditLogs")
                        .HasForeignKey("proj_id");

                    b.HasOne("NPI.Server.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("user_id");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NPI.Server.Models.Comments", b =>
                {
                    b.HasOne("NPI.Server.Models.Projects", "Project")
                        .WithMany("Comments")
                        .HasForeignKey("proj_id");

                    b.HasOne("NPI.Server.Models.Tasks", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("task_id");

                    b.HasOne("NPI.Server.Models.Users", "User")
                        .WithMany("Comments")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NPI.Server.Models.Departments", b =>
                {
                    b.HasOne("NPI.Server.Models.Projects", null)
                        .WithMany("Departments")
                        .HasForeignKey("Projectsproj_id");
                });

            modelBuilder.Entity("NPI.Server.Models.DocumentTypes", b =>
                {
                    b.HasOne("NPI.Server.Models.Departments", "Department")
                        .WithMany("DocumentTypes")
                        .HasForeignKey("dept_id");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("NPI.Server.Models.Enquiries", b =>
                {
                    b.HasOne("NPI.Server.Models.Users", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("created_by")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPI.Server.Models.Customers", "Customer")
                        .WithMany()
                        .HasForeignKey("cust_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPI.Server.Models.Projects", "Project")
                        .WithMany()
                        .HasForeignKey("proj_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("NPI.Server.Models.EnquiryCustomerRef", b =>
                {
                    b.HasOne("NPI.Server.Models.Enquiries", "Enquiry")
                        .WithOne("CustomerRef")
                        .HasForeignKey("NPI.Server.Models.EnquiryCustomerRef", "enquiry_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enquiry");
                });

            modelBuilder.Entity("NPI.Server.Models.EnquiryGeneralInfo", b =>
                {
                    b.HasOne("NPI.Server.Models.Enquiries", "Enquiry")
                        .WithOne("GeneralInfo")
                        .HasForeignKey("NPI.Server.Models.EnquiryGeneralInfo", "enquiry_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enquiry");
                });

            modelBuilder.Entity("NPI.Server.Models.EnquirySealInfo", b =>
                {
                    b.HasOne("NPI.Server.Models.Enquiries", "Enquiry")
                        .WithOne("SealInfo")
                        .HasForeignKey("NPI.Server.Models.EnquirySealInfo", "enquiry_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enquiry");
                });

            modelBuilder.Entity("NPI.Server.Models.Files", b =>
                {
                    b.HasOne("NPI.Server.Models.Departments", "Department")
                        .WithMany("Files")
                        .HasForeignKey("dept_id");

                    b.HasOne("NPI.Server.Models.DocumentTypes", "DocumentType")
                        .WithMany("Files")
                        .HasForeignKey("doc_type_id");

                    b.HasOne("NPI.Server.Models.Enquiries", "Enquiry")
                        .WithMany("Files")
                        .HasForeignKey("enquiry_id");

                    b.HasOne("NPI.Server.Models.Projects", "Project")
                        .WithMany("Files")
                        .HasForeignKey("proj_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPI.Server.Models.Files", "ReplacedByFile")
                        .WithMany()
                        .HasForeignKey("replaced_by")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NPI.Server.Models.Tasks", "Task")
                        .WithMany("Files")
                        .HasForeignKey("task_id");

                    b.HasOne("NPI.Server.Models.Users", "UploadByUser")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("upload_by")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("DocumentType");

                    b.Navigation("Enquiry");

                    b.Navigation("Project");

                    b.Navigation("ReplacedByFile");

                    b.Navigation("Task");

                    b.Navigation("UploadByUser");
                });

            modelBuilder.Entity("NPI.Server.Models.Milestones", b =>
                {
                    b.HasOne("NPI.Server.Models.Projects", "Project")
                        .WithMany("Milestones")
                        .HasForeignKey("proj_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPI.Server.Models.Departments", "ResponsibleDepartment")
                        .WithMany("Milestones")
                        .HasForeignKey("responsible_dept_id");

                    b.HasOne("NPI.Server.Models.Tasks", "Tasks")
                        .WithOne("Milestone")
                        .HasForeignKey("NPI.Server.Models.Milestones", "task_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("ResponsibleDepartment");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("NPI.Server.Models.Notifications", b =>
                {
                    b.HasOne("NPI.Server.Models.Projects", "Project")
                        .WithMany("Notifications")
                        .HasForeignKey("proj_id");

                    b.HasOne("NPI.Server.Models.Users", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NPI.Server.Models.ProjectRevisions", b =>
                {
                    b.HasOne("NPI.Server.Models.Projects", "Project")
                        .WithMany()
                        .HasForeignKey("proj_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPI.Server.Models.Users", "RevisedByUser")
                        .WithMany()
                        .HasForeignKey("revised_by")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("RevisedByUser");
                });

            modelBuilder.Entity("NPI.Server.Models.ProjectStatusHistory", b =>
                {
                    b.HasOne("NPI.Server.Models.Users", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("changed_by")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPI.Server.Models.Projects", "Project")
                        .WithMany("ProjectStatusHistories")
                        .HasForeignKey("proj_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("NPI.Server.Models.ProjectTeams", b =>
                {
                    b.HasOne("NPI.Server.Models.Users", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("assigned_by")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NPI.Server.Models.Projects", "Project")
                        .WithMany("ProjectTeams")
                        .HasForeignKey("proj_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPI.Server.Models.Users", "User")
                        .WithMany("ProjectTeams")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NPI.Server.Models.Projects", b =>
                {
                    b.HasOne("NPI.Server.Models.Users", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("created_by")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NPI.Server.Models.Customers", "Customer")
                        .WithMany("Projects")
                        .HasForeignKey("cust_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPI.Server.Models.Users", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("updated_by")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("NPI.Server.Models.RolePermissions", b =>
                {
                    b.HasOne("NPI.Server.Models.Roles", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NPI.Server.Models.TaskRevisions", b =>
                {
                    b.HasOne("NPI.Server.Models.Departments", "Department")
                        .WithMany()
                        .HasForeignKey("dept_id");

                    b.HasOne("NPI.Server.Models.ProjectRevisions", "Revision")
                        .WithMany("TaskRevisions")
                        .HasForeignKey("revision_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NPI.Server.Models.Tasks", "Task")
                        .WithMany("TaskRevisions")
                        .HasForeignKey("task_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Revision");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("NPI.Server.Models.Tasks", b =>
                {
                    b.HasOne("NPI.Server.Models.Users", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("assigned_by")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NPI.Server.Models.Users", "AssignedToUser")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("assigned_to");

                    b.HasOne("NPI.Server.Models.Departments", "Department")
                        .WithMany("Tasks")
                        .HasForeignKey("dept_id");

                    b.HasOne("NPI.Server.Models.Tasks", "ParentTask")
                        .WithMany("SubTasks")
                        .HasForeignKey("parent_task_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NPI.Server.Models.Projects", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("proj_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("AssignedToUser");

                    b.Navigation("Department");

                    b.Navigation("ParentTask");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("NPI.Server.Models.UserSessions", b =>
                {
                    b.HasOne("NPI.Server.Models.Users", "User")
                        .WithMany("UserSessions")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NPI.Server.Models.Users", b =>
                {
                    b.HasOne("NPI.Server.Models.Departments", "Department")
                        .WithMany("Users")
                        .HasForeignKey("dept_id");

                    b.HasOne("NPI.Server.Models.Roles", "Role")
                        .WithMany("Users")
                        .HasForeignKey("role_id");

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NPI.Server.Models.Customers", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("NPI.Server.Models.Departments", b =>
                {
                    b.Navigation("DocumentTypes");

                    b.Navigation("Files");

                    b.Navigation("Milestones");

                    b.Navigation("Tasks");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NPI.Server.Models.DocumentTypes", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("NPI.Server.Models.Enquiries", b =>
                {
                    b.Navigation("CustomerRef");

                    b.Navigation("Files");

                    b.Navigation("GeneralInfo");

                    b.Navigation("SealInfo");
                });

            modelBuilder.Entity("NPI.Server.Models.Files", b =>
                {
                    b.Navigation("Approvals");
                });

            modelBuilder.Entity("NPI.Server.Models.ProjectRevisions", b =>
                {
                    b.Navigation("TaskRevisions");
                });

            modelBuilder.Entity("NPI.Server.Models.Projects", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("AuditLogs");

                    b.Navigation("Comments");

                    b.Navigation("Departments");

                    b.Navigation("Files");

                    b.Navigation("Milestones");

                    b.Navigation("Notifications");

                    b.Navigation("ProjectStatusHistories");

                    b.Navigation("ProjectTeams");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("NPI.Server.Models.Roles", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NPI.Server.Models.Tasks", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Comments");

                    b.Navigation("Files");

                    b.Navigation("Milestone");

                    b.Navigation("SubTasks");

                    b.Navigation("TaskRevisions");
                });

            modelBuilder.Entity("NPI.Server.Models.Users", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("AssignedTasks");

                    b.Navigation("Comments");

                    b.Navigation("Notifications");

                    b.Navigation("ProjectTeams");

                    b.Navigation("UploadedFiles");

                    b.Navigation("UserSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
